### PR TITLE
fix(queryAllByAttribute): query `input` elements with dynamically assigned value

### PR DESCRIPTION
**Pull request by eunjae-lee**
**What**: The implementation of `queryAllByAttribute` has been changed so that it can successfully query `input` elements with dynamically assigned `value`.

**Why**: When `value` is dynamically assigned to an `input`, not by an attribute on HTML, `queryAllByAttribute` won't query that element at the moment.

**How**: `queryAllByAttribute` behaves differently when its `attribute` is equal to `"value"`. I'm not sure if this is the best way to implement this. Feedbacks are welcomed.

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by eunjae-lee** [comment]
closes #158

**Comment by eunjae-lee** [comment]
Thoughts? @alexkrolick

**Comment by kentcdodds** [comment]
I don't like this. I might be inclined to add a new query called `queryByProperty` which compares DOM node properties directly rather than `getAttribute`. I honestly don't really like getting by attributes or properties because those are not typically visible to the end user. Getting by the `value` property of an `input` is acceptable though because the value of an input _is_ visible to the user.... Hmmm...

What do you think @alexkrolick?

**Comment by kentcdodds** [comment]
True. We do have [`getBySelectText`](https://github.com/kentcdodds/dom-testing-library#getbyselecttext) perhaps we should do `getByInputText` and `getByTextAreaText` as well?

**Comment by sompylasar** [comment]
The only reason for querying by attribute is because the attributes are proxies to what the browser displays to the user (there's no good way to query the browser render tree itself and get anmotated positioned semantic items out of it).

**Comment by alexkrolick** [comment]
Maybe the queries for select value and textarea could be combined with the input query - `getByCurrentValue`? This would smooth over the select value in the same way React does it.

I think this would work for  most use cases because the value property and the DOM attribute are initially in sync when an element is created, and when they are different, the property is what is visually displayed. 

https://codepen.io/alexkrolick/pen/NELEKE?editors=1011

**Comment by kentcdodds** [comment]
Ok, I'm in favor of that. Let's go ahead and add it and we can add a deprecation message to the README for the `getBySelectText`. Then we can officially remove it in a future breaking change (when we have sufficient justification to break stuff).

Thanks for the PR anyway @eunjae-lee! Would you be interested in making a PR to add a `getByCurrentValue` query?

**Comment by eunjae-lee** [comment]
Thanks all for the feedbacks. I really love how this conclusion has been made!

@kentcdodds I'm still interested in contributing on this. To make sure, `getByCurrentValue` will refer to value property or (if not exists) DOM attribute, right?

**Comment by kentcdodds** [comment]
I think the property should be sufficient.

**Comment by eunjae-lee** [comment]
Hmm. Although value property hasn't been assigned to the element, if it has DOM attribute, end-user will see it on screen. Shouldn't we get elements like this?

**Comment by alexkrolick** [comment]
The value property is initially set to the same thing as the attribute, unless I'm interpreting this wrong (check console) https://codepen.io/alexkrolick/pen/NELEKE?editors=1011

**Comment by eunjae-lee** [comment]
@alexkrolick oh you're right.

**Pull request closed without merging**
