### PR TITLE
fit(TS): Update TypeScript definitions for getQueriesForElement change

### PR DESCRIPTION
**Pull request by pbomb**
**What**:

Updated the TypeScript definitions to match the change from bindElementToQueries to getQueriesForElement

**Why**:

The TS definitions are out of date and are showing the wrong/old function being available.

**How**:

Renamed the file and its exported function

**Checklist**:

* [x] Documentation
* [x] Tests
* [x] Ready to be merged 
* [x] Added myself to contributors table 

I also update the CONTRIBUTING.md file to remove the `-s` flag to the `setup` NPM script as the script already adds that flag.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Whoops, I just realized that I let a typo slip through in the commit message. I'll push a manual release 👌

**Comment by pbomb** [comment]
Cool, thanks. Did I make the typo?

**Comment by kentcdodds** [comment]
We both did. The commit said `fit` and I didn't notice until after clicking the merge button 😅 No big deal though.

**Comment by pbomb** [comment]
🤦‍♂️ oops, sorry. don't know how that happened. 🤷‍♂️ thanks for resolving the issue!

**Pull request merged**
