### PR TITLE
ci: test Node.js 8, 10 and 11

### PR DESCRIPTION
**Pull request by DanielRuf**
**What**:

All supported Node.js versions should be tested to catch any issues on newer LTS releases.

**Why**:

To ensure that there are no breaking builds on Node.js 6, 10 and 11.

**How**:

Updated the Travis CI config.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by alexkrolick** [comment]
Node 6 is not supported, but other than that this is a good idea

**Comment by DanielRuf** [comment]
> Node 6 is not supported, but other than that this is a good idea

See the engines field which says `node >= 6`.

**Comment by DanielRuf** [comment]
> Node 6 is not supported, but other than that this is a good idea

If so, it should be `node >= 8` in the `engines` field.

**Comment by DanielRuf** [comment]
https://github.com/kentcdodds/dom-testing-library/blob/master/package.json#L24

**Comment by kentcdodds** [comment]
Thanks!

**Pull request merged**
