### PR TITLE
docs: added Using Without Jest section

### PR DESCRIPTION
**Pull request by dadamssg**
**What**:
Added Using Without Jest docs section

**Why**:
There is setup required.

**How**:
Edited the readme

**Checklist**:

* [x] Documentation
* [ ] Tests N/A
* [x] Ready to be merged 
* [x] Added myself to contributors table

### CODE REVIEW

**Comment by dadamssg** [comment]
image

And further down

image

I was thinking that in the `react-testing-library` readme I could create a PR to add that "See Using Without Jest" link but link it to the new section in this repo so it's not just duplicated. Or I can just add it there to. Whatever you think is best.

Let me know if the verbiage needs adjusting.

**Comment by kentcdodds** [comment]
Let me know what you think of my revisions! Please try it out and make sure it works 😅

**Comment by kentcdodds** [comment]
Oh, and simply linking to this documentation from react-testing-library sounds fine to me.

**Comment by dadamssg** [comment]
Looks good to me!

image

**Comment by kentcdodds** [comment]
Thanks!

**Pull request merged**
