### PR TITLE
fixed small typo

### PR DESCRIPTION
**Pull request by shairez**
**What**:
fixed a small typo

**Why**:
I have OCD

**How**:
By the power invested in me via my keyboard

**Checklist**:

- [x] Documentation
- [ ] Tests N/A
- [x] Ready to be merged 
- [ ] Added myself to contributors table N/A

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome! I'm glad! Have you seen this? https://github.com/timdeschryver/ngx-testing-library#readme

**Comment by shairez** [comment]
Haven't heard about it, looks nice! 

There is also [Spectator](https://github.com/NetanelBasal/spectator) which uses your lib.
Both look similar.

I'm aiming to solve the same problem from a different angle.
Also have a different approach on how to test more "smarter" components without paying the cost of rendering and setup but without the need to shallow render (to be able to break my tests on a child component mismatch), and without going full integration.

I'm considering using this lib with the `within` function to decorate my object with its functionality. 

Currently experimenting with it, will update.

**Comment by kentcdodds** [comment]
Interesting! The `within` function is definitely the intended composition mechanism for libraries that build on top of dom-testing-library. I'd love to have a *-testing-library for every framework considering they're generally fairly small and easy to write and because the philosophy is to not care about implementation details almost all frameworks can be tested in almost exactly the same way which I think is a very good thing :)

Good luck!

**Comment by shairez** [comment]
Thanks brother! 
Yeah, as I said, I like the simplicity. 

Keep up the good work!

**Pull request merged**
