### PR TITLE
allow queryAllByText to select text nodes text content

### PR DESCRIPTION
**Pull request by tylerthehaas**
closes issue #207

### CODE REVIEW

**Comment by kentcdodds** [comment]
@all-contributors please add @tylerthehaas for code and tests

**Comment by gnapse** [comment]
After this was merged, I'm getting `container.matches is not a function` using `cypress-testing-library`. Any ideas why this could be?

**Comment by kentcdodds** [comment]
Hmmmm.. could you figure out what's going on? Maybe we need to just do a typeof check?

**Comment by gnapse** [comment]
I'll try to carve out time to attempt to create a minimal reproduction repo, if no one has a brilliant idea before I can do that.

I initially suspected this `element.matches` thing was not supported by Cypress browser environment (as it happens, for instance, with `EventTarget`) but that seems unlikely, since that element method [seems to have full support across all browsers](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches).

**Comment by tylerthehaas** [comment]
Its interesting that its breaking for the `getByLabelText` query since all that was changed was `queryAllByText` and as far as I can tell that isn't called anywhere within `getByLabelText`.

**Comment by tylerthehaas** [comment]
The issue here is that cypress testing library is passing the document as the container. We should be able to do a check to make sure that `container.matches` is a function and that should solve this.

**Comment by kentcdodds** [comment]
Agreed 👍

**Comment by cslinmiso** [comment]
` TypeError: container.matches is not a function` is happening to me too, while I was passing `window.document` to `getByText` in jest.

**Comment by valscion** [comment]
I've got a working fix for this, with a new test case that would fail. I'll create a PR shortly

**Pull request merged**
