### PR TITLE
fix: upgrade wait-for-expect to 1.0.0

### PR DESCRIPTION
**Pull request by SimenB**
**What**:
Dep upgrade

**Why**:
I noticed I got both 0.4.0 and 1.0.0 in my lockfile when installing react-testing-library

**How**:
GitHub UI

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by SimenB** [comment]
If you rerun the build, it's gone, IIRC. You retrigger that specific build, you don't generate a new one

**Comment by kentcdodds** [comment]
Are there breaking changes in the library?

**Comment by lgandecki** [comment]
Good question. If it works it works by passing the tests, it works - the only change is in the way we export the function (so you no longer have to use .default in some cases).
Since we import (not require) it doesn’t matter.
 It is breaking - hence the change of the version, but not in our (dom-testing-library) case.

**Comment by kentcdodds** [comment]
Super 👍 thanks friends!

**Pull request merged**
